### PR TITLE
Test for keys that are too long or too short.

### PR DESCRIPTION
**Pull request by millette**
I noticed a problem with keys of 65 characters, where the last character was silently dropped. This catches that case.

For instance:
https://datbase.org/view?query=26620b74b6878c872ff243a151974aad5d52349bda12a02c19098421fce8bef4ab

But the correct URL should be without the extra "ab":
https://datbase.org/view?query=26620b74b6878c872ff243a151974aad5d52349bda12a02c19098421fce8bef4

Both currently return the same dat.

### CODE REVIEW

**Comment by juliangruber** [comment]
I wouldn't consider this a bug, what's the problem if you add some characters that aren't meaningful?

**Comment by millette** [comment]
It's sort of odd to be able to pad an **ID** with junk and still have it work. So "AB...C" (64chars) is the same as "AB...C12", it's just weird and unexpected.

**Comment by mafintosh** [comment]
:+1: on merging this, keys are always 64 chars

**Comment by juliangruber** [comment]
wouldn't the a simpler solution then be this regexp instead?

```js
/\/?([^/]{64})$/
```

**Comment by juliangruber** [comment]
i was making it open ended because who knew what url parameters we would put afterwards

**Comment by millette** [comment]
I just tried your suggested regex and it failed unit tests.

**Comment by millette** [comment]
If dat-encoding doesn't throw on *invalid* keys, we have to deal with it upstream in all cases.

**Comment by juliangruber** [comment]
maybe i also just don't understand your implementation, why is it important to consider the 65 characters case in the regexp?

**Comment by millette** [comment]
I don't get exactly why, but a 65 char string is converted to a buffer of length 32, as if the string had only 64 chars. There might be a more elegant way to solve this.

In any case, I added the tests to make sure my implementation was ok.

**Comment by juliangruber** [comment]
in dubio pro test case, let's release this :)

**Comment by juliangruber** [comment]
Published as 5.0.0, as this is breaking behavior

**Comment by millette** [comment]
Oh my https://en.wikipedia.org/wiki/In_dubio_pro_reo

J'en perds mon latin ;-)

Thanks for the merge and major version change.

**Comment by juliangruber** [comment]
C'est okay Robin :)

**Pull request merged**
